import {Link} from 'wouter';
import {Hero,SectionHeading,SecondaryButton,PrimaryButton,CTASection,Reveal,PageMeta} from '../components/Layout';
import {StatStrip,ImageTextSection,ServiceFeature,TeamGrid,LogoGrid,ValueCard} from '../components/Content';
import {ContactSection} from '../components/Contact';
import {pageCopy,sectionCopy,valueDescriptions,aircraftValueFlow,serviceImages,serviceImageAlts,leadershipIntro,servicesOverview} from '../content/site';
import {companyOverview,mission,vision,coreValues} from '../content/company';
import {services} from '../content/services';
import {airlineClients,aircraftOwnersLessors,aviationServicesTechnicalPartners,industryOrganizations,academicPartners,canopyPartner,groupCollaborators} from '../content/clientsAndPartners';
function Intro({page}:{page:keyof typeof pageCopy}){return <><PageMeta title={pageCopy[page].label} description={pageCopy[page].description}/><Hero {...pageCopy[page]}/></>}
export function AboutPage(){return <><Intro page="about"/><ImageTextSection label="ABOUT WINGBOX AVIATION" title={sectionCopy.aboutCompanyTitle} image="aircraft.jpg">{companyOverview.paragraphs.map(p=><p key={p}>{p}</p>)}</ImageTextSection><StatStrip/><section className="section pale purpose-section"><div className="container"><SectionHeading label="OUR PURPOSE" title={sectionCopy.purposeTitle}/><div className="purpose-grid"><div className="mission-grid"><article><span className="statement-mark" aria-hidden="true">◎</span><h2>MISSION</h2><p>{mission}</p></article><article><span className="statement-mark" aria-hidden="true">◉</span><h2>VISION</h2><p>{vision}</p></article></div><div className="values-grid">{coreValues.map((v,i)=><ValueCard key={v} title={v} body={valueDescriptions[i]} index={i}/>)}</div></div></div></section></>}
export function ServicesPage(){return <><Intro page="services"/><section className="section pale services-overview"><div className="container split"><SectionHeading label="OUR SERVICES" title={servicesOverview.title} description={servicesOverview.body}/><div className="overview-pillars">{servicesOverview.pillars.map((p,i)=><div key={p}><span aria-hidden="true">{["◎","✓","◇","✈"][i]}</span><h3>{p}</h3></div>)}</div></div></section><section className="section services-modules"><div className="container">{services.map((s,i)=><section id={s.slug} key={s.slug}><ServiceFeature service={s} index={i}/></section>)}</div></section><CTASection/></>}
export function CanopyFeature(){return <ImageTextSection label="WINGBOX × CANOPY" title="TECHNICAL TRAINING THROUGH CANOPY" image="advisory.webp" alt="Documentation and professional collaboration"><LogoGrid names={[canopyPartner]}/><p>{services[1].purpose}</p><ol className="process-flow">{services[1].contentAreas.map(a=><li key={a}>{a}</li>)}</ol><SecondaryButton href={`/services/${services[1].slug}`}>LEARN ABOUT THE PROGRAM</SecondaryButton></ImageTextSection>}
export function ServiceDetailPage({slug}:{slug:string}){const index=services.findIndex(s=>s.slug===slug);const s=services[index];if(!s)return <NotFoundPage/>;return <><PageMeta title={s.name} description={s.purpose}/><Hero label={`SERVICE ${s.number}`} title={s.name} description={s.purpose} image={serviceImages[index]} imageAlt={serviceImageAlts[index]}/><section className="section"><div className="container service-detail"><aside><Link href="/services" className="text-link">← ALL SERVICES</Link><nav aria-label="Other services">{services.map(item=><Link key={item.slug} href={`/services/${item.slug}`} aria-current={item.slug===slug?'page':undefined}>{item.number} / {item.name}</Link>)}</nav></aside><Reveal><SectionHeading title={index===1?'FROM ACADEMIC KNOWLEDGE TO CAREER READINESS':'FOCUSED SUPPORT FOR YOUR REQUIREMENTS'} description={s.purpose}/><ul className={index===1?'process-flow':'detail-capabilities'}>{s.contentAreas.map((a,i)=><li key={a}><span>{String(i+1).padStart(2,'0')}</span>{a}</li>)}</ul>{index===6&&<p>{companyOverview.paragraphs[3]}</p>}{index===1&&<><h3>ACADEMIC PARTNERS</h3><LogoGrid names={academicPartners} className="academic-logos"/></>}<PrimaryButton href="/contact">{index===1?'LEARN ABOUT THE PROGRAM →':'DISCUSS YOUR REQUIREMENT →'}</PrimaryButton></Reveal></div></section><CTASection/></>}
export function TeamPage(){return <><Intro page="team"/><section className="section pale team-section"><Reveal className="container"><div className="leadership-heading"><SectionHeading label={sectionCopy.leadershipLabel} title={sectionCopy.teamTitle}/><p>{leadershipIntro}</p></div><TeamGrid/></Reveal></section></>}
export function ClientsPage(){return <><Intro page="clients"/><section className="section pale clients-section"><div className="container partner-sections">{[['AIRLINE CLIENTS',airlineClients],['AIRCRAFT OWNERS / LESSORS',aircraftOwnersLessors],['AVIATION SERVICES / TECHNICAL PARTNERS',aviationServicesTechnicalPartners.slice(0,4)],['INDUSTRY ORGANIZATIONS',industryOrganizations]].map(([title,names])=><Reveal key={title as string}><SectionHeading title={title as string}/><LogoGrid names={names as string[]}/></Reveal>)}</div><div className="container partner-sections"><Reveal className="group-collaborators"><SectionHeading title="GROUP / TECHNICAL COLLABORATORS"/><LogoGrid names={groupCollaborators}/><Link className="text-link" href={`/services/${services[1].slug}`}>TECHNICAL TRAINING THROUGH CANOPY →</Link></Reveal></div></section><section className="section academic-section"><div className="container"><SectionHeading label="ACADEMIC PARTNERS" title={sectionCopy.academicTitle}/><LogoGrid names={academicPartners} className="academic-logos"/></div></section><section className="section pale"><Reveal className="container"><SectionHeading title={sectionCopy.valueTitle} description={sectionCopy.valueBody}/><ol className="value-flow">{aircraftValueFlow.map((a,i)=><li key={a}><span>{String(i+1).padStart(2,'0')}</span><h3>{a}</h3></li>)}</ol></Reveal></section><CTASection/></>}
export function ContactPage(){return <><Intro page="contact"/><ContactSection/><CTASection/></>}
export function NotFoundPage(){return <section className="section not-found container"><PageMeta title="Page not found" description="Explore Wingbox Aviation technical services."/><p className="eyebrow">404</p><h1>THIS PAGE IS NOT ON OUR FLIGHT PLAN</h1><p>Find the aviation support you need through our services or contact our team.</p><PrimaryButton href="/">RETURN HOME →</PrimaryButton></section>}
