import {useEffect,useRef,useState} from 'react';
import {animate,useInView,useReducedMotion} from 'framer-motion';
import {Link} from 'wouter';
import {statistics} from '../content/company';
import {services,type Service} from '../content/services';
import {leadership,type TeamMember} from '../content/team';
import {logoAssets,serviceImages} from '../content/site';
import {Reveal,SectionHeading,SecondaryButton} from './Layout';
function Count({value}:{value:string}){const ref=useRef<HTMLSpanElement>(null);const visible=useInView(ref,{once:true});const reduced=useReducedMotion();const [count,setCount]=useState(reduced?parseInt(value):0);useEffect(()=>{if(!visible)return;if(reduced){setCount(parseInt(value));return}const control=animate(0,parseInt(value),{duration:1.2,onUpdate:v=>setCount(Math.round(v))});return()=>control.stop()},[visible,value,reduced]);return <span ref={ref}>{count}+</span>}
export function StatStrip(){return <section className="stat-strip" aria-label="Company statistics"><div className="container stat-grid">{statistics.map(s=><div className="stat" key={s.label} data-confirmed={s.confirmed}><strong><Count value={s.value}/></strong><p>{s.label}</p>{!s.confirmed&&<small>Pending confirmation</small>}</div>)}</div></section>}
export function ImageTextSection({title,label,children,image='airport.jpg',alt='Aircraft on the apron'}:{title:string;label?:string;children:React.ReactNode;image?:string;alt?:string}){return <section className="section pale"><Reveal className="container split"><div><SectionHeading label={label} title={title}/>{children}</div><div className="image-frame"><img src={`/images/${image}`} alt={alt} loading="lazy"/></div></Reveal></section>}
export function ServiceCard({service,index}:{service:Service;index:number}){return <Link href={`/services/${service.slug}`} className="service-card"><img src={`/images/${serviceImages[index]}`} alt="" loading="lazy"/><div><span className="service-number">{service.number}</span><h3>{service.name}</h3><p>{service.purpose}</p><span className="card-link">EXPLORE SERVICE <span>↗</span></span></div></Link>}
export function ServiceFeature({service,index}:{service:Service;index:number}){return <Reveal className={`service-feature ${index%2?'reverse':''} ${index===3?'featured-service':''}`}><img src={`/images/${serviceImages[index]}`} alt={service.name.toLowerCase().includes('advisory')?'Technical advisory documentation':'Commercial aircraft operations'} loading="lazy"/><div><span className="service-number">{service.number} / TECHNICAL SERVICES</span><h2>{service.name}</h2><p>{service.purpose}</p><ul className="capability-list">{service.contentAreas.map(a=><li key={a}>{a}</li>)}</ul><SecondaryButton href={`/services/${service.slug}`}>LEARN MORE</SecondaryButton></div></Reveal>}
export function ServicesGrid(){return <div className="service-grid">{services.map((s,i)=><ServiceCard key={s.slug} service={s} index={i}/>)}</div>}
export function TeamCard({member,onOpen}:{member:TeamMember;onOpen:()=>void}){const initials=member.name.replace('ENGR. ','').split(' ').filter(n=>n.length>2).map(n=>n[0]).slice(0,2).join('');return <button className="team-card" onClick={onOpen} aria-label={`View profile of ${member.name}`}><div className="portrait-placeholder"><span>{initials}</span><small>WINGBOX AVIATION</small></div><div className="team-card-copy"><h3>{member.name}</h3><p>{member.position}</p><span className="card-link">VIEW PROFILE <span>↗</span></span></div></button>}
export function TeamProfileModal({member,onClose}:{member:TeamMember;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const dialog=ref.current;const previous=document.activeElement as HTMLElement;dialog?.showModal();return()=>{dialog?.close();previous?.focus()}},[]);return <dialog ref={ref} className="profile-modal" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}} aria-labelledby="profile-name"><button className="modal-close" onClick={onClose} aria-label="Close profile">✕</button><div className="profile-mark" aria-hidden="true">W</div><h2 id="profile-name">{member.name}</h2><p className="role">{member.position}</p>{member.bio&&<p>{member.bio}</p>}{member.expertise&&<><h3>AREAS OF EXPERTISE</h3><ul className="capability-list">{member.expertise.map(e=><li key={e}>{e}</li>)}</ul></>}</dialog>}
export function TeamGrid(){const [selected,setSelected]=useState<TeamMember|null>(null);return <><div className="team-grid">{leadership.map(m=><TeamCard member={m} key={m.name} onOpen={()=>setSelected(m)}/>)}</div>{selected&&<TeamProfileModal member={selected} onClose={()=>setSelected(null)}/>}</>}
export function LogoGrid({names}:{names:string[]}){return <div className="logo-grid">{names.map(n=><div key={n} className="logo-cell">{logoAssets[n]?<img src={`/images/${logoAssets[n]}.webp`} alt={n} loading="eager"/>:<span>{n}</span>}</div>)}</div>}
export function LogoCarousel({names}:{names:string[]}){return <LogoGrid names={names}/>}
export function ValueCard({title,body,index}:{title:string;body:string;index:number}){return <article className="value-card"><span className="value-index">{String(index+1).padStart(2,'0')}</span><h3>{title}</h3><p>{body}</p></article>}
export function TestimonialCard({quote,name}:{quote:string;name:string}){return <figure className="testimonial"><blockquote>{quote}</blockquote><figcaption>{name}</figcaption></figure>}
