import {useEffect,useRef,useState,type ReactNode} from 'react';
import {Link,useLocation} from 'wouter';
import {motion,useReducedMotion,useScroll,useMotionValueEvent} from 'framer-motion';
import logo from '../assets/logo/wingbox-logo.png';
import {navigation,emails,phone,offices} from '../content/contact';
import {services} from '../content/services';
import {brandTagline} from '../content/company';
import {sectionCopy} from '../content/site';
export function Reveal({children,className=''}:{children:ReactNode;className?:string}) {
  const reduce=useReducedMotion();
  // Keep offscreen content visible for fast scrolling, captures, and delayed observers.
  // Animate only on entry; the shallow fade never makes a whole section disappear.
  return <motion.div className={className} initial={false}
    whileInView={reduce?{opacity:1,y:0}:{opacity:[.85,1],y:[20,0]}}
    viewport={{once:true,amount:0}}
    transition={{type:'tween',duration:reduce?0:.55,ease:[.22,.61,.36,1]}}>
    {children}
  </motion.div>;
}
export function PrimaryButton({href,children}:{href:string;children:ReactNode}){return <Link href={href} className="button primary">{children}</Link>}
export function SecondaryButton({href,children}:{href:string;children:ReactNode}){return <Link href={href} className="text-link">{children} <span aria-hidden="true">→</span></Link>}
export function MobileMenu({close}:{close:()=>void}) {const ref=useRef<HTMLElement>(null);useEffect(()=>{const prev=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.querySelector<HTMLElement>('a')?.focus();return()=>{document.body.style.overflow=prev}},[]);return <nav ref={ref} id="mobile-menu" className="mobile-menu" aria-label="Mobile navigation" onKeyDown={e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const items=ref.current?.querySelectorAll<HTMLElement>('a,button');if(!items?.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}>{navigation.map(n=><Link key={n.href} href={n.href} onClick={close}>{n.label}<span>↗</span></Link>)}<button onClick={close} className="button">Close menu</button></nav>}
export function Header(){const [location]=useLocation();const [open,setOpen]=useState(false);const [scrolled,setScrolled]=useState(false);const toggle=useRef<HTMLButtonElement>(null);const {scrollY}=useScroll();useMotionValueEvent(scrollY,'change',y=>setScrolled(y>40));const close=()=>{setOpen(false);toggle.current?.focus()};useEffect(()=>setOpen(false),[location]);return <header className={`header ${scrolled?'scrolled':''}`}><div className="header-inner"><Link href="/" aria-label="Wingbox Aviation home"><img src={logo} className="logo" alt="Wingbox Aviation Inc." /></Link><nav className="desktop-nav" aria-label="Main navigation">{navigation.map(n=><Link href={n.href} key={n.href} aria-current={location===n.href || n.href==='/services'&&location.startsWith('/services/')?'page':undefined}>{n.label}</Link>)}</nav><Link className="button primary header-cta" href="/contact">GET IN TOUCH <span>→</span></Link><button ref={toggle} className="menu-toggle" aria-expanded={open} aria-controls={open?'mobile-menu':undefined} aria-label={open?'Close navigation':'Open navigation'} onClick={()=>open?close():setOpen(true)}>{open?'✕':'☰'}</button></div>{open&&<MobileMenu close={close}/>}</header>}
export function Hero({label,title,description,home=false,image='airport.jpg'}:{label:string;title:string;description:string;home?:boolean;image?:string}){return <section className={`hero ${home?'hero-home':''}`}><img className="hero-image" src={`/images/${image}`} alt={image==='advisory.webp'?'Technical consultation and documentation':image==='aircraft.jpg'?'Aircraft wing above the clouds':'Commercial aircraft at an airport'} fetchPriority="high"/><div className="hero-shade"/><div className="container hero-content"><Reveal><p className="eyebrow light">{label}</p><h1>{title}</h1><p className="hero-description">{description}</p>{home&&<PrimaryButton href="/services">EXPLORE OUR SERVICES <span>→</span></PrimaryButton>}</Reveal></div><div className="stripes" aria-hidden="true"/></section>}
export function SectionHeading({label,title,description}:{label?:string;title:string;description?:string}){return <div className="section-heading">{label&&<p className="eyebrow">{label}</p>}<h2>{title}</h2>{description&&<p>{description}</p>}</div>}
export function CTASection(){return <section className="cta"><div className="container cta-inner"><div><h2>{sectionCopy.ctaTitle}</h2><p>{sectionCopy.ctaBody}</p></div><PrimaryButton href="/contact">CONTACT US <span>→</span></PrimaryButton></div></section>}
export function Footer(){return <footer><div className="container footer-grid"><div><Link href="/"><img className="footer-logo" src={logo} alt="Wingbox Aviation Inc."/></Link><p className="tagline">{brandTagline}</p></div><div><h3>QUICK LINKS</h3>{navigation.map(n=><Link key={n.href} href={n.href}>{n.label}</Link>)}</div><div><h3>SERVICES</h3>{services.map(s=><Link key={s.slug} href={`/services/${s.slug}`}>{s.name}</Link>)}</div><div><h3>GET IN TOUCH</h3><p>{offices[0].lines.join(' ')}</p><a href="tel:+63495010799">{phone}</a>{emails.map(e=><a key={e} href={`mailto:${e}`}>{e}</a>)}</div></div><div className="container copyright">© {new Date().getFullYear()} Wingbox Aviation Inc. All Rights Reserved.</div></footer>}
export function PageMeta({title,description}:{title:string;description:string}){const [location]=useLocation();useEffect(()=>{document.title=`${title} | Wingbox Aviation Inc.`;const meta=document.querySelector('meta[name="description"]');meta?.setAttribute('content',description);window.scrollTo({top:0,behavior:'instant'})},[title,description,location]);return null}
